name: "🕷️ Bug report"
description: Report errors or unexpected behavior
labels:
- Issue-Bug
- Needs-Triage
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/microsoft/PowerToys/issues) before filing a new one!

- id: version
  type: input
  attributes:
    label: Microsoft DevHub version
    placeholder: 0.0.1
  validations:
    required: true

- id: toolareas
  type: dropdown
  attributes:
    label: Area(s) with issue? 
    description: What tools had an issue? Check all that apply. 
    multiple: true
    options:
      - "Tool 1"
      - "Tool 2"
      - "Tool 3"

- id: repro
  type: textarea
  attributes:
    label: Steps to reproduce
    description: We highly suggest including screenshots.
    placeholder: Having detailed steps helps us reproduce the bug. 
  validations:
    required: true

- id: expectedbehavior
  type: textarea
  attributes:
    label: ✔️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: false

- id: actualbehavior
  type: textarea
  attributes:
    label: ❌ Actual Behavior
    placeholder: What happened instead?
  validations:
    required: false

- id: includedsysinfo
  type: textarea
  attributes:
    label: Included System Information
    placeholder: i.e. CPU, Memory usage 
  validations:
    required: false

- id: othersoftware
  type: textarea
  attributes:
    label: Other Software
    description: If you're reporting a bug about our interaction with other software, what software is being used? What versions? 
    placeholder: i.e. OS Build version, .NET version, WinAppSDK version
  validations:
    required: false