name: "⭐ Suggest a feature/improvement"
description: Propose something new.
labels:
- Needs-Triage
body:
- id: toolareas
  type: dropdown
  attributes:
    label: Area(s) with issue? 
    description: What tools had an issue? Check all that apply. 
    multiple: true
    options:
      - "Tool 1"
      - "Tool 2"
      - "Tool 3"
- id: description
  type: textarea
  attributes: 
    label: Description of the new feature / enhancement
    description: Please limit one request per issue.
    placeholder: What is the expected behavior of the proposed feature?
  validations:
    required: true
- id: scenario
  type: textarea
  attributes:
    label: Scenario when this would be used?
    placeholder: What is the scenario this would be used? Why is this important to your workflow as a power user?
  validations:
    required: true
- id: supportinginfo
  type: textarea
  attributes:
    label: Supporting information
    placeholder: "Having additional evidence, data, tweets, blog posts, research, ... anything is extremely helpful. This information provides context to the scenario that may otherwise be lost."
  validations:
    required: false
